# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 561)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Bg = QtWidgets.QLabel(self.centralwidget)
        self.Bg.setGeometry(QtCore.QRect(-30, -20, 1131, 601))
        self.Bg.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Bg.setText("")
        self.Bg.setScaledContents(False)
        self.Bg.setObjectName("Bg")
        self.bg_border = QtWidgets.QLabel(self.centralwidget)
        self.bg_border.setGeometry(QtCore.QRect(0, 0, 1051, 561))
        self.bg_border.setStyleSheet("color: rgb(0, 0, 0);\n"
                "background-color: rgb(0, 0, 0);\n"
                "border : 2px Solid White;\n"
                "")
        self.bg_border.setText("")
        self.bg_border.setObjectName("bg_border")
        self.Gif = QtWidgets.QLabel(self.centralwidget)
        self.Gif.setGeometry(QtCore.QRect(10, 10, 1051, 561))
        self.Gif.setStyleSheet("border : 1px solid white;\n"
"\n"
"")


        self.Gif.setText("")
        self.Gif.setPixmap(QtGui.QPixmap("muth.gif"))
        self.Gif.setScaledContents(True)
        self.Gif.setObjectName("Gif")
        MainWindow.setCentralWidget(self.centralwidget)
        
        
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(780, 510, 131, 41))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                "font: 16pt \"MS Shell Dlg 2\";\n"
                "color: rgb(255, 255, 255);\n"
                "border : 1px solid white;\n"
                "")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "START"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    app.windowIcon("icon_jarvis.ico")
    sys.exit(app.exec_())
